sudo: required

language: node_js
node_js:
  - "8"

before_install:
  - echo "Testing Before Install"
  - npm install
  - bundle install

install:
  - bundle exec jekyll build

after_success:
  - echo "Build Test Success"
